title: Delightfully-Damaged DevOps
description: Tales of Horror, Amusement, and Triumph from the Front Lines

url: http://commercecraft.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: mrbanzai
   twitter: mrbanzai
   facebook: mr.michael.porter
   email: michael@commerececraft.com

google_analytics: "UA-39761658-3"
